### ISSUE TITLE
polkit crashes when the LogTarget D-Bus property is set

### ISSUE THREAD

**Issue by evverx** [polkit-org/polkit#506]
**Describe the bug**
```sh
$ busctl set-property org.freedesktop.PolicyKit1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogTarget "s" ''
Failed to set property LogTarget on interface org.freedesktop.LogControl1: Remote peer disconnected
```
```
#0  0x00007f11e1a80724 in __pthread_kill_implementation () from target:/lib64/libc.so.6
#1  0x00007f11e1a27d0e in raise () from target:/lib64/libc.so.6
#2  0x00007f11e1a0f942 in abort () from target:/lib64/libc.so.6
#3  0x00007f11e24e414c in g_assertion_message[cold] () from target:/lib64/libglib-2.0.so.0
#4  0x00007f11e25538c7 in g_assertion_message_expr () from target:/lib64/libglib-2.0.so.0
#5  0x00007f11e270887d in invoke_set_property_in_idle_cb () from target:/lib64/libgio-2.0.so.0
#6  0x00007f11e2527add in g_idle_dispatch () from target:/lib64/libglib-2.0.so.0
#7  0x00007f11e252128c in g_main_context_dispatch_unlocked.lto_priv () from target:/lib64/libglib-2.0.so.0
#8  0x00007f11e25817f8 in g_main_context_iterate_unlocked.isra () from target:/lib64/libglib-2.0.so.0
#9  0x00007f11e2527377 in g_main_loop_run () from target:/lib64/libglib-2.0.so.0
#10 0x0000000000403a32 in main (argc=<optimized out>, argv=<optimized out>) at ../src/polkitbackend/polkitd.c:294
```
**To Reproduce**
```sh
busctl set-property org.freedesktop.PolicyKit1 /org/freedesktop/LogControl1 org.freedesktop.LogControl1 LogTarget "s" ''
```
It can also be triggered by just running dfuzzer (FYI @mrc0mmand)

**Expected behavior**
It shouldn't crash.

Looks like it's from 79d84d0dd0dd7d16c616555acf8cd14862d02baf

**Comment by vmihalko** [comment]
Should `LogTarget` be configurable? If not, this bug is likely due to a copy-paste error on the following line https://github.com/polkit-org/polkit/blob/885537205ab76653faee4972986966f6faadcc48/src/polkitbackend/polkitbackendauthority.c#L661 The fix would simply involve setting `access=read`. Is that correct, @bluca? If so, I can take care of this fix.

**Comment by evverx** [comment]
According to the specification (https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.LogControl1.html) it should be configurable (and privileged):
```sh
      @org.freedesktop.DBus.Property.EmitsChangedSignal("false")
      @org.freedesktop.systemd1.Privileged("true")
      readwrite s LogTarget = '...';
...
Those two properties are writable, so they may be set by sufficiently privileged users.
```
Currently this API is kind of half-implemented though so personally I think it can safely be reverted and brought back once the logging in general (including that `--no-debug` option) is sorted out.

**Comment by evverx** [comment]
FWIW polkit no longer logs things like
```
Operator of unix-process:177488:2009823 FAILED to authenticate to gain authorization for action ...
```
by default (and that's why I started looking at what was introduced in v125 and that PR in particular in the first place). I agree that it's reasonable to only allow setting the log target to syslog but I still think it would be great to maybe revisit the logging part in general.

**Comment by evverx** [comment]
In the meantime I opened https://github.com/polkit-org/polkit/issues/512 because it can be discussed separately probably.

The "no-debug" option still hides things like
```
Oct 22 20:31:00 default polkitd[773]: g_dbus_method_invocation_get_message: assertion 'G_IS_DBUS_METHOD_INVOCATION (invocation)' failed
Oct 22 20:31:00 default polkitd[773]: g_dbus_message_get_unix_fd_list: assertion 'G_IS_DBUS_MESSAGE (message)' failed
Oct 22 20:31:15 default polkitd[773]: g_dbus_method_invocation_get_message: assertion 'G_IS_DBUS_METHOD_INVOCATION (invocation)' failed
Oct 22 20:31:15 default polkitd[773]: g_dbus_message_get_unix_fd_list: assertion 'G_IS_DBUS_MESSAGE (message)' failed
Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
```
even when the LogLevel D-Bus property is set to debug but that's a separate and long-known issue.

**Comment by jrybar-rh** [comment]
> In the meantime I opened #512 because it can be discussed separately probably.
> 
> The "no-debug" option still hides things like
> 
> ```
> Oct 22 20:31:00 default polkitd[773]: g_dbus_method_invocation_get_message: assertion 'G_IS_DBUS_METHOD_INVOCATION (invocation)' failed
> Oct 22 20:31:00 default polkitd[773]: g_dbus_message_get_unix_fd_list: assertion 'G_IS_DBUS_MESSAGE (message)' failed
> Oct 22 20:31:15 default polkitd[773]: g_dbus_method_invocation_get_message: assertion 'G_IS_DBUS_METHOD_INVOCATION (invocation)' failed
> Oct 22 20:31:15 default polkitd[773]: g_dbus_message_get_unix_fd_list: assertion 'G_IS_DBUS_MESSAGE (message)' failed
> Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
> Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
> Oct 22 20:31:16 default polkitd[773]: g_error_free: assertion 'error != NULL' failed
> ```
> 
> even when the LogLevel D-Bus property is set to debug but that's a separate and long-known issue.

That's exactly why `--no-debug` was left there. The loglevel defines the verbosity to syslog, but `--no-debug` suppresses output of Glib-related messages. Maybe we could rename the option, so it's clearer OR (if worth discussion) make changes so the Glib messages are routed through polkit_backend_log() into syslog too.

**Comment by evverx** [comment]
> That's exactly why --no-debug was left there

I agree that at this point it should be kept. What I was trying to say is that there are essentially two different logging mechanisms and LogLevel affects only one of them. Ideally the logging part would be more straightforward and LogLevel would control all the logs (at least that's how systemd and its daemons work and that's where the Log* knobs make sense). In its current form I'm not sure what the D-Bus API is trying to accomplish. That's all. As far as I can the no-debug option is being discussed in https://github.com/polkit-org/polkit/pull/425 in general so if it's kept it's on its way to be documented better.

**Comment by jrybar-rh** [comment]
Unlike polkit, systemd is not Glib-intensive. The Dbus API plays a major part in LogLevel and polkit itself, because polkit communicates with other software that uses libpolkit (or doesn't and goes rogue over Dbus, right) over dbus and LogControl's role (IIUC) is to manage logging of affiliated services universally.
On some places of polkit, g_error/g_message functions are used instead of syslog because PolkitAuthority object is not present in those parts of code (as @bluca once pointed out correctly). But considering the higher attention to this part it may make sense to replace `PolkitBackendAuthority *authority` with a different "init'd" indicator in `polkit_backend_authority_log()` and route all messages through there. The number of replacements of glib calls would be massive though and also not as granular as syslog levels, which might cause log floods.

**Comment by evverx** [comment]
> LogControl's role (IIUC) is to manage logging of affiliated services universally

That's correct and as a heavy user of that API I think it's useful as long as it works. It's kind of handy to, for example, forward resolved logs to `null` to prevent it from complaining about weird stuff networkd tries to supply to it when it's fuzzed with its log level set to debug to catch soft "assertions" and things like that. It's not possible to do any of those things with polkit currently and it's necessary to manually edit the unit file to see/drop all the messages anyway.

Given how hard it is to implement it maybe documenting the shortcomings can suffice in the short term if it should be kept to cover basic use cases. Either way I still think it can safely be reverted but it's just my opinion.
